[package]
name = "chat_application"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server/server.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[dependencies]
chrono = "0.4.24"
env_logger = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.17"
log4rs = "1.2.0"
